'use client';

import { useEffect } from 'react';

// ─────────────────────────────────────────────────────────────────────────────
// Generated by Surge AI
// Stack: Next.js 14 · TypeScript · Tailwind CSS
//
// This page renders the AI-generated website using dangerouslySetInnerHTML so
// that the Tailwind CDN classes, custom CSS, and vanilla JS all work as-is.
//
// To convert this to proper TSX components:
//   1. Break the HTML body into React components in src/components/
//   2. Replace dangerouslySetInnerHTML with JSX
//   3. Move styles to Tailwind classes or CSS modules
//   4. Remove the Tailwind CDN <Script> from layout.tsx
// ─────────────────────────────────────────────────────────────────────────────

const pageBody = `
    <nav class="fixed w-full bg-black bg-opacity-70 glass p-4 text-white transition">
        <div class="container mx-auto flex justify-between items-center">
            <a href="#" class="text-2xl font-bold">Your Restaurant Name</a>
            <div>
                <a href="#menu" class="mr-4 hover:text-red-500 transition">Menu</a>
                <a href="#contact" class="hover:text-red-500 transition">Contact</a>
            </div>
        </div>
    </nav>

    <section id="hero" class="h-screen flex items-center justify-center bg-cover bg-center" style="background-image: url('https://images.unsplash.com/photo-1551022378-802c1c7070c4?auto=format&fit=crop&w=1600&q=90');">
        <div class="text-center">
            <h1 class="text-5xl font-bold mb-4">Experience Luxury Dining</h1>
            <p class="mb-8">Chennai's Finest South Indian Cuisine</p>
            <a href="#menu" class="bg-red-600 px-6 py-3 text-lg font-semibold rounded-full hover:bg-red-500 transition">View Menu</a>
        </div>
    </section>

    <section id="menu" class="py-16 bg-gray-900 text-white">
        <div class="container mx-auto">
            <h2 class="text-3xl font-bold text-center mb-8">Our Menu</h2>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
                <div class="glass p-6 rounded-lg transition hover:shadow-lg">
                    <img onerror="this.onerror=null;this.src='https://source.unsplash.com/1600x1000/?Dosa&sig=101';" loading="lazy" src="https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=800&q=90" alt="Dosa" class="w-full h-48 object-cover rounded-lg mb-4">
                    <h3 class="text-xl font-semibold mb-2">Dosa</h3>
                    <p class="mb-2">Crispy and delicious South Indian crepe. ₹50</p>
                    <button class="bg-red-600 px-4 py-2 rounded-full hover:bg-red-500 transition">Add to Cart</button>
                </div>
                <!-- More product cards -->
            </div>
        </div>
    </section>

    <section id="contact" class="py-16 bg-black text-white">
        <div class="container mx-auto">
            <h2 class="text-3xl font-bold text-center mb-8">Contact Us</h2>
            <div class="flex flex-col md:flex-row md:justify-between items-center">
                <div class="mb-8 md:mb-0 md:w-1/2">
                    <p>Address: Velachery, Chennai, India</p>
                    <p>Phone: +91 7010190110</p>
                    <p>Email: support@workfast.ai</p>
                    <div class="mt-4">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3916.9085396673613!2d80.22097731462297!3d13.035812290824774!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a5267d10b4f3b2f%3A0x4d1d2e3e0e9b3f6b!2sVelachery%2C%20Chennai%2C%20Tamil%20Nadu%2C%20India!5e0!3m2!1sen!2sus!4v1637068495290!5m2!1sen!2sus" width="100%" height="200" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                    </div>
                </div>
                <form class="md:w-1/2 bg-white text-black p-8 rounded-lg shadow-lg glass">
                    <h3 class="text-2xl font-bold mb-4">Get in Touch</h3>
                    <input type="text" placeholder="Name" class="w-full p-2 mb-4 border rounded-lg">
                    <input type="text" placeholder="Phone" class="w-full p-2 mb-4 border rounded-lg">
                    <textarea placeholder="Message" class="w-full p-2 mb-4 border rounded-lg"></textarea>
                    <button type="submit" class="bg-red-600 px-4 py-2 text-white rounded-full hover:bg-red-500 transition">Submit</button>
                </form>
            </div>
        </div>
    </section>

    <footer class="py-4 bg-black text-center text-white">
        <p>&copy; 2023 Your Restaurant Name. All Rights Reserved.</p>
    </footer>

`;
const pageScripts = `
(() => {
  const smoothScrollToHash = (hash) => {
    if (!hash || hash === '#') return;
    const id = decodeURIComponent(hash.slice(1));
    const target = document.getElementById(id) || document.querySelector(hash);
    if (target) target.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };
  document.addEventListener('click', (event) => {
    const a = event.target.closest('a[href]');
    if (!a) return;
    const href = (a.getAttribute('href') || '').trim();
    if (!href || href === '#') {
      event.preventDefault();
      return;
    }
    if (href.startsWith('#')) {
      event.preventDefault();
      history.replaceState(null, '', href);
      smoothScrollToHash(href);
      return;
    }
    // Block any non-hash navigation from escaping iframe context.
    event.preventDefault();
  });
  window.addEventListener('hashchange', () => smoothScrollToHash(location.hash));
})();
`;

export default function Home() {
  useEffect(() => {
    if (!pageScripts.trim()) return;
    try {
      const script = document.createElement('script');
      script.textContent = pageScripts;
      document.body.appendChild(script);
      return () => {
        try { document.body.removeChild(script); } catch (_) {}
      };
    } catch (e) {
      console.warn('Script execution warning:', e);
    }
  }, []);

  return (
    <div dangerouslySetInnerHTML={{ __html: pageBody }} />
  );
}
